name: Create qa builds

jobs:
  android_qa_build:
    name: Build Android
    type: build
    params:
      platform: android
      profile: qa
  ios_device_qa_build:
    name: Build iOS device
    type: build
    params:
      platform: ios
      profile: qa
